### PR TITLE
Adjust color palette to look more asteroidOS styled

### PR DESCRIPTION
**Pull request by moWerk**
shot-diamonds-1D

Create new color palette based on the AsteroidOS app colors.
- 2 & 4 left desaturated according to the original colors 
- 8- 64 gradually getting red from yellow
- 128- 512 all three digits blueish
- 1024 & 2048 violet and pink highlights
- 4096 added in striking red

compiled version to try (copy to /usr/bin/ and restart ceres)
[asteroid-diamonds.zip](https://github.com/AsteroidOS/asteroid-diamonds/files/11151499/asteroid-diamonds.zip)

### CODE REVIEW

**Comment by moWerk** [comment]
Color palette mock-ups here
https://github.com/AsteroidOS/asteroid-media/tree/main/apps/asteroid-diamonds

**Review by MagneFire — APPROVED** [review]
Thanks for your work on this PR!

After the latest changes I'm now happy with how the game looks.

**Comment by moWerk** [comment]
Which is like so
image

**Comment by FlorentRevest** [comment]
Thanks, that's a great improvement!

**Pull request merged**
